import { defineConfig, Plugin } from "vite";
import * as path from "@std/path";

const __filename = path.fromFileUrl(import.meta.url);
const __dirname = path.dirname(__filename);

function cssToTsPlugin(): Plugin {
  let cssContent = '';
  
  return {
    name: 'css-to-ts',
    enforce: 'post',
    
    generateBundle(_options, bundle) {
      // Find the CSS asset in the bundle
      for (const [fileName, asset] of Object.entries(bundle)) {
        if (asset.type === 'asset' && fileName.endsWith('.css')) {
          cssContent = asset.source as string;
          
          // Create a TypeScript file that exports the CSS as a string
          this.emitFile({
            type: 'asset',
            fileName: 'styles.ts',
            source: `// Auto-generated by Vite build process
export const styles = ${JSON.stringify(cssContent)};
`
          });
          
          break;
        }
      }
    }
  };
}

export default defineConfig({
  root: ".",
  build: {
    outDir: "../plugin-vite/generated",
    emptyOutDir: true,
    rollupOptions: {
      input: {
        styles: path.resolve(__dirname, "./src/styles.css"),
      },
      output: {
        assetFileNames: "[name][extname]",
      },
    },
  },
  css: {
    transformer: 'lightningcss',
    lightningcss: {
      drafts: {
        customMedia: true,
      }
    },
  },
  plugins: [cssToTsPlugin()],
});
